# Generated by Django 5.0.2 on 2024-04-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_initial_price_alter_order_shippingprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_price',
        ),
    ]
